definitions:
  order.CreateOrderCommand:
    properties:
      orderLines:
        items:
          $ref: '#/definitions/order.OrderLine'
        type: array
      orderNumber:
        type: string
      price:
        $ref: '#/definitions/shared.Money'
    type: object
  order.OrderLine:
    properties:
      id:
        type: string
      price:
        $ref: '#/definitions/shared.Money'
      sku:
        type: string
    type: object
  orders.Order:
    properties:
      finalPrice:
        $ref: '#/definitions/shared.Money'
      id:
        type: string
      orderNumber:
        type: string
      paymentRejectReason:
        type: string
      paymentStatus:
        type: string
      price:
        $ref: '#/definitions/shared.Money'
    type: object
  shared.Money:
    properties:
      currencyCode:
        type: string
      value:
        type: number
    type: object
info:
  contact: {}
paths:
  /v1/orders/:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: c
        required: true
        schema:
          $ref: '#/definitions/order.CreateOrderCommand'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/orders.Order'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
  /v1/orders/orderNumber/{orderNumber}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Order Number
        in: path
        name: orderNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
swagger: "2.0"
