version: "3.3"

services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo:latest
    expose:
      - 30000
    ports:
      - 30000:30000
    restart: always
    command: "--bind_ip_all --replSet rs0 --port 30000"
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:latest
    expose:
      - 30001
    ports:
      - 30001:30001
    restart: always
    command: "--bind_ip_all --replSet rs0 --port 30001"
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:latest
    expose:
      - 30002
    ports:
      - 30002:30002
    restart: always
    command: "--bind_ip_all --replSet rs0 --port 30002"

# 1. Host dosyasına aşağıdakileri ekleyin

# 127.0.0.1 mongo0
# 127.0.0.1 mongo1
# 127.0.0.1 mongo2

# 2. Mongo node'larından birine bağlanın

# docker exec -it mongo0 mongo --port 30000

# 3. Mongo replicaset konfigurasyon kodunu node'da çalışın

# rs.initiate({"_id":"rs0","members":[{"_id":0,"host":"mongo0:30000"},{"_id":1,"host":"mongo1:30001"},{"_id":2,"host":"mongo2:30002"}]});
