version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: "mongo-tripinvest"
    restart: always
    volumes:
      - ~/docker-volume/mongo-tripinvest:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    container_name: "mongo-express-tripinvest"
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=Sa123456
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log

# 1. Host dosyasına aşağıdakileri ekleyin

# 127.0.0.1 mongo0
# 127.0.0.1 mongo1
# 127.0.0.1 mongo2

# 2. Mongo node'larından birine bağlanın

# docker exec -it mongo0 mongo --port 30000

# 3. Mongo replicaset konfigurasyon kodunu node'da çalışın

# rs.initiate({"_id":"rs0","members":[{"_id":0,"host":"mongo0:30000"},{"_id":1,"host":"mongo1:30001"},{"_id":2,"host":"mongo2:30002"}]});
